id: P007890
initial_creation_type: ocr
source_metadata:
  id: bdr:W3PD394
  title: འགོག་གླིང་།
  author: ''
  volumes:
    fd69624acc544c37af9d48df1f620031:
      image_group_id: I2PD17700
      title: ''
      volume_number: 1
      total_pages: 462
    5d622e740e2e476fa18ea41dbb2d4e28:
      image_group_id: I2PD17701
      title: ''
      volume_number: 2
      total_pages: 508
ebook_metadata:
  title: འགོག་གླིང་།
  author: ''
  sku: P007890
  cover: cover.jpg
  layers:
  - pagination
