id: I7B0CEBE4
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T08:22:54+00:00'
last_modified: '2022-06-09T07:07:16.984590+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3PD394
  title: འགོག་གླིང་།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    '4142':
      image_group_id: I2PD17700
      title: Volume 1 of 'gog gling /
      total_pages: 462
      order: 1
      base_file: 4142.txt
    AA34:
      image_group_id: I2PD17701
      title: Volume 2 of 'gog gling /
      total_pages: 508
      order: 2
      base_file: AA34.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
